apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow-azure-sso.secretName" . }}
  labels:
    {{- include "mlflow-azure-sso.labels" . | nindent 4 }}
type: Opaque
stringData:
  MLFLOW_FLASK_SERVER_SECRET_KEY: {{ .Values.flaskServerSecretKey | quote }}
  PG_PASSWORD: {{ .Values.postgres.password | quote }}
  {{- if .Values.azureSso.enabled }}
  OIDC_CLIENT_SECRET: {{ .Values.azureSso.clientSecret | quote }}
  {{- end }}
