"""Issue, list, delete and verify users' named access tokens (issue #189).

Plaintext format: ``mlf_<prefix>_<secret>``, presented as the password of HTTP basic auth.

* ``prefix`` is 8 random hex characters. It is not secret: it is stored in clear so that
  :meth:`UserTokenRepository.authenticate` can fetch the one candidate row by index and verify a
  single hash, however many tokens the user holds. Hashing the presented value against every
  token of the user would let anyone who knows a username make each request cost as many hash
  verifications as that user has tokens.
* ``secret`` is ``secrets.token_urlsafe(32)`` — 256 bits.

A secret carried over from ``users.password_hash`` by the migration has no prefix. Each user holds
at most one such token (named ``default``); it is found by being the user's only prefix-less row,
so it too costs one hash. Replacing it through :meth:`UserTokenRepository.replace` issues a
prefixed token, and prefix-less rows are never created again.

The plaintext is returned exactly once, from :meth:`create` and :meth:`replace`, and never again.
"""

import secrets
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Callable, List, Optional, Tuple

from mlflow.exceptions import MlflowException
from mlflow.protos.databricks_pb2 import INTERNAL_ERROR, INVALID_PARAMETER_VALUE, INVALID_STATE, RESOURCE_ALREADY_EXISTS, RESOURCE_DOES_NOT_EXIST
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session
from werkzeug.security import check_password_hash, generate_password_hash

from mlflow_oidc_auth.db.models import SqlUser, SqlUserToken
from mlflow_oidc_auth.logger import get_logger
from mlflow_oidc_auth.repository.user import normalize_username
from mlflow_oidc_auth.repository.utils import get_user

logger = get_logger()

# Hash method for access tokens (issue #336), and for SCIM tokens, which import it from here.
#
# Nothing in this plugin stores a human-chosen password. Every token is generated by
# :func:`generate_token` — ``secrets.token_urlsafe(32)``, 256 bits — and no endpoint accepts an
# operator-supplied secret. A memory-hard KDF exists to make brute-forcing *low-entropy* human
# passwords expensive; against 256 bits there is nothing to brute-force, so the ~48 ms that
# Werkzeug's default scrypt costs would buy no security while being paid on every
# basic-authenticated request. Verification with this method takes ~0.08 ms.
#
# The cost argument also assumes **one** hash per request. That is what the prefix lookup in
# :meth:`UserTokenRepository.authenticate` guarantees; verifying against every token of a user
# would multiply it by the number of tokens, and has to stay out.
#
# Hashes written before #336 used scrypt and still verify: the method is encoded in the stored
# hash and ``check_password_hash`` dispatches on it. They are never re-hashed in place; a secret
# moves to this method when its token is replaced.
#
# This is intentionally a constant, not configuration. It is a property of what we store, not a
# deployment choice, and the failure mode of setting it wrong is silent. ``TestTokenEntropyPremise``
# in ``tests/repository/test_user_token_hashing.py`` pins the token's format and entropy, so a
# change that weakens the premise fails a test instead of passing quietly. If one of those tests
# has to be updated, this constant has to be re-justified in the same diff.
TOKEN_HASH_METHOD = "pbkdf2:sha256:1000"

TOKEN_SCHEME = "mlf"
PREFIX_LENGTH = 8

#: The name of the token ``PATCH /users/access-token`` replaces, and of the secret the migration
#: carried over from ``users.password_hash``.
DEFAULT_TOKEN_NAME = "default"

#: How many tokens one user may hold. Expired ones are cleared whenever a token is issued, so this
#: bounds the table, and anything that lists it; twenty is more than any person or pipeline needs.
MAX_LIVE_TOKENS_PER_USER = 20

#: The longest lifetime a token may be issued with. One year, with a day of slack for time zones.
MAX_TOKEN_LIFETIME = timedelta(days=366)

#: ``last_used_at`` is refreshed at most this often per token. Writing it on every request would
#: turn every basic-authenticated read into a write; to the minute is all an operator needs to
#: tell a live token from a forgotten one.
LAST_USED_RESOLUTION_SECONDS = 60

MAX_NAME_LENGTH = 255


def _now() -> datetime:
    """Naive UTC, matching how every other timestamp in this schema is stored."""
    return datetime.now(timezone.utc).replace(tzinfo=None)


def _naive_utc(value: datetime) -> datetime:
    if value.tzinfo is not None:
        value = value.astimezone(timezone.utc).replace(tzinfo=None)
    return value


def _iso(value: Optional[datetime]) -> Optional[str]:
    return value.replace(tzinfo=timezone.utc).isoformat() if value else None


def generate_token() -> Tuple[str, str]:
    """Return ``(prefix, plaintext)`` for a new token."""
    prefix = secrets.token_hex(PREFIX_LENGTH // 2)
    return prefix, f"{TOKEN_SCHEME}_{prefix}_{secrets.token_urlsafe(32)}"


def parse_prefix(plaintext: str) -> Optional[str]:
    """Extract the lookup prefix from a presented token, or None if it carries none.

    A secret from before this format is 24 letters and digits, so it can never parse as one.
    """
    if not isinstance(plaintext, str):
        return None
    parts = plaintext.split("_", 2)
    if len(parts) != 3 or parts[0] != TOKEN_SCHEME or len(parts[1]) != PREFIX_LENGTH or not parts[2]:
        return None
    return parts[1]


@dataclass(frozen=True)
class UserTokenRecord:
    """A token as the rest of the system sees it. Deliberately carries no hash."""

    id: int
    name: str
    token_prefix: Optional[str]
    created_at: datetime
    created_by: Optional[str]
    expires_at: datetime
    last_used_at: Optional[datetime]

    def is_live(self, now: Optional[datetime] = None) -> bool:
        return self.expires_at > (now or _now())

    def to_json(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "token_prefix": self.token_prefix,
            "created_at": _iso(self.created_at),
            "created_by": self.created_by,
            "expires_at": _iso(self.expires_at),
            "last_used_at": _iso(self.last_used_at),
            "active": self.is_live(),
        }


def _record(row: SqlUserToken) -> UserTokenRecord:
    return UserTokenRecord(
        id=row.id,
        name=row.name,
        token_prefix=row.token_prefix,
        created_at=row.created_at,
        created_by=row.created_by,
        expires_at=row.expires_at,
        last_used_at=row.last_used_at,
    )


def _validate_name(name: Optional[str]) -> str:
    name = (name or "").strip()
    if not name:
        raise MlflowException("a token needs a name", INVALID_PARAMETER_VALUE)
    if len(name) > MAX_NAME_LENGTH:
        raise MlflowException(f"a token name may be at most {MAX_NAME_LENGTH} characters", INVALID_PARAMETER_VALUE)
    return name


def _validate_expiry(expires_at: datetime, now: datetime) -> datetime:
    if not isinstance(expires_at, datetime):
        raise MlflowException("a token needs an expiration", INVALID_PARAMETER_VALUE)
    expires_at = _naive_utc(expires_at)
    if expires_at <= now:
        raise MlflowException("the expiration must be in the future", INVALID_PARAMETER_VALUE)
    if expires_at > now + MAX_TOKEN_LIFETIME:
        raise MlflowException("the expiration must be less than 1 year in the future", INVALID_PARAMETER_VALUE)
    return expires_at


class UserTokenRepository:
    """Reads and writes ``user_tokens``."""

    def __init__(self, session_maker):
        self._Session: Callable[..., Session] = session_maker

    @staticmethod
    def _lock_user(session, username: str) -> SqlUser:
        """The user row, locked for the rest of the transaction (``SELECT ... FOR UPDATE``).

        Issuing a token must not interleave with deactivating the user or with another issue for
        the same user: deactivation deletes the user's tokens, and an insert that read ``active``
        before that commit would leave a token behind; two concurrent replacements of ``default``
        would both delete the old row and then collide on the name. The lock makes each wait for
        the other.

        SQLite has no row locks and ignores ``FOR UPDATE``, and its driver begins a transaction only
        at the first write, so a plain read would see ``active`` before a concurrent deactivation
        commits. A no-op write to the row takes SQLite's database write lock first, and the row is
        then re-read under it. On PostgreSQL the row is already locked and the write changes nothing.
        """
        username = normalize_username(username)
        user = session.query(SqlUser).filter(SqlUser.username == username).with_for_update().one_or_none()
        if user is None:
            raise MlflowException(f"User with username={username} not found", RESOURCE_DOES_NOT_EXIST)
        session.query(SqlUser).filter(SqlUser.id == user.id).update({SqlUser.id: SqlUser.id}, synchronize_session=False)
        session.refresh(user)
        return user

    @staticmethod
    def _purge_expired(session, user: SqlUser, now: datetime) -> None:
        """Delete the user's expired tokens. They can never authenticate again; clearing them on
        every issue keeps the table bounded by the cap, however short the lifetimes a user keeps
        requesting, and frees their names for reuse."""
        session.query(SqlUserToken).filter(SqlUserToken.user_id == user.id, SqlUserToken.expires_at <= now).delete(synchronize_session=False)

    def _insert(self, session, user: SqlUser, name: str, expires_at: datetime, created_by: Optional[str], now: datetime) -> Tuple[SqlUserToken, str]:
        if not user.active:
            # A deactivated account keeps no credentials; a token issued now would come back to
            # life on reactivation without anyone having issued it to an active user.
            raise MlflowException(f"'{user.username}' is deactivated; tokens cannot be issued", INVALID_STATE)
        # By now ``create`` has refused an existing name and ``replace`` has deleted it, so every
        # remaining row is another live token.
        if session.query(SqlUserToken.id).filter(SqlUserToken.user_id == user.id).count() >= MAX_LIVE_TOKENS_PER_USER:
            raise MlflowException(
                f"'{user.username}' already holds {MAX_LIVE_TOKENS_PER_USER} unexpired tokens; delete one first",
                INVALID_STATE,
            )
        # A 32-bit prefix collides rarely but not never. Checked before inserting; the unique
        # index is the backstop for a concurrent insert, and a collision there is retried inside a
        # savepoint rather than reported as something it is not.
        for _ in range(5):
            prefix, plaintext = generate_token()
            if session.query(SqlUserToken.id).filter(SqlUserToken.token_prefix == prefix).first() is not None:
                continue
            row = SqlUserToken(
                user_id=user.id,
                name=name,
                token_prefix=prefix,
                token_hash=generate_password_hash(plaintext, method=TOKEN_HASH_METHOD),
                created_at=now,
                created_by=created_by,
                expires_at=expires_at,
            )
            try:
                with session.begin_nested():
                    session.add(row)
                    session.flush()
            except IntegrityError as e:
                constraint = str(getattr(e, "orig", e))
                if "token_prefix" in constraint:
                    continue
                if "uq_user_tokens_user_id_name" in constraint or "user_tokens.name" in constraint:
                    raise MlflowException(f"a token named '{name}' already exists", RESOURCE_ALREADY_EXISTS) from None
                raise MlflowException("could not issue the token", INTERNAL_ERROR) from None
            return row, plaintext
        raise MlflowException("could not allocate a unique token prefix", INTERNAL_ERROR)

    def create(self, username: str, name: str, expires_at: datetime, created_by: Optional[str]) -> Tuple[UserTokenRecord, str]:
        """Issue a new named token. Returns the record and the plaintext, never retrievable again.

        The user's expired tokens are deleted in the same transaction.

        Raises:
            MlflowException: ``INVALID_PARAMETER_VALUE`` for an empty or over-long name or an
                expiry that is past or more than a year away; ``RESOURCE_ALREADY_EXISTS`` if the
                user already has a token of that name; ``INVALID_STATE`` at the per-user cap or for
                a deactivated user; ``RESOURCE_DOES_NOT_EXIST`` for an unknown user.
        """
        name = _validate_name(name)
        now = _now()
        expires_at = _validate_expiry(expires_at, now)
        with self._Session(read_only=False) as session:
            user = self._lock_user(session, username)
            self._purge_expired(session, user, now)
            if session.query(SqlUserToken.id).filter(SqlUserToken.user_id == user.id, SqlUserToken.name == name).first() is not None:
                raise MlflowException(f"a token named '{name}' already exists", RESOURCE_ALREADY_EXISTS)
            row, plaintext = self._insert(session, user, name, expires_at, created_by, now)
            return _record(row), plaintext

    def replace(self, username: str, name: str, expires_at: datetime, created_by: Optional[str]) -> Tuple[UserTokenRecord, str, bool]:
        """Issue a token named ``name``, deleting any existing token of that name in the same
        transaction. What ``PATCH /users/access-token`` does to the ``default`` token.

        Returns:
            The new record, its plaintext, and whether a token was replaced.

        Raises:
            MlflowException: As :meth:`create`, except that an existing name is replaced rather
                than refused.
        """
        name = _validate_name(name)
        now = _now()
        expires_at = _validate_expiry(expires_at, now)
        with self._Session(read_only=False) as session:
            user = self._lock_user(session, username)
            self._purge_expired(session, user, now)
            replaced = session.query(SqlUserToken).filter(SqlUserToken.user_id == user.id, SqlUserToken.name == name).delete(synchronize_session=False)
            session.flush()
            row, plaintext = self._insert(session, user, name, expires_at, created_by, now)
            return _record(row), plaintext, bool(replaced)

    def list(self, username: str) -> List[UserTokenRecord]:
        """Every token of ``username``, expired ones included, oldest first."""
        with self._Session() as session:
            user = get_user(session, normalize_username(username))
            rows = session.query(SqlUserToken).filter(SqlUserToken.user_id == user.id).order_by(SqlUserToken.id).all()
            return [_record(row) for row in rows]

    def delete(self, username: str, token_id: int) -> UserTokenRecord:
        """Delete one token of ``username``. Effective on the token's next use.

        Raises:
            MlflowException: ``RESOURCE_DOES_NOT_EXIST`` if ``username`` holds no token with that
                id — another user's token reads exactly like one that does not exist.
        """
        with self._Session(read_only=False) as session:
            user = get_user(session, normalize_username(username))
            row = session.query(SqlUserToken).filter(SqlUserToken.id == token_id, SqlUserToken.user_id == user.id).one_or_none()
            if row is None:
                raise MlflowException(f"token {token_id} not found", RESOURCE_DOES_NOT_EXIST)
            record = _record(row)
            session.delete(row)
            session.flush()
            return record

    def delete_all(self, username: str) -> int:
        """Delete every token of ``username``. Returns how many were deleted."""
        with self._Session(read_only=False) as session:
            user = get_user(session, normalize_username(username))
            count = session.query(SqlUserToken).filter(SqlUserToken.user_id == user.id).delete(synchronize_session=False)
            session.flush()
            return count

    def authenticate(self, username: str, plaintext: str) -> bool:
        """Whether ``plaintext`` is a live token of ``username``.

        One indexed lookup — by prefix, or for a carried-over secret by being the user's one
        prefix-less row — then one constant-time hash verification. The prefix is not secret, so
        an early return for an unknown one leaks nothing an attacker could not read off a token
        they hold. Whether the account may authenticate at all (``active``) is decided by the
        caller, on the profile it reads anyway.
        """
        if not isinstance(plaintext, str) or not plaintext:
            return False
        username = normalize_username(username)
        prefix = parse_prefix(plaintext)
        now = _now()
        with self._Session(read_only=False) as session:
            query = session.query(SqlUserToken).join(SqlUser, SqlUser.id == SqlUserToken.user_id).filter(SqlUser.username == username)
            if prefix is not None:
                query = query.filter(SqlUserToken.token_prefix == prefix)
            else:
                query = query.filter(SqlUserToken.token_prefix.is_(None))
            row = query.order_by(SqlUserToken.id).first()
            if row is None:
                return False
            if not check_password_hash(row.token_hash, plaintext):
                return False
            if row.expires_at <= now:
                return False
            if row.last_used_at is None or (now - row.last_used_at).total_seconds() >= LAST_USED_RESOLUTION_SECONDS:
                row.last_used_at = now
                session.flush()
            return True
